### ISSUE TITLE
Positon of liveui button (in all themes)

### ISSUE THREAD

**Issue by genofire** [mmcc/videojs-themes#7]

**Comment by mmcc** [comment]
Hi there, can we get some more information on this one?

**Comment by genofire** [comment]
e.g. the live button is at this theme not in same vertical high then the quality selector: 
![20201012_21h42m56s_grim](https://user-images.githubusercontent.com/6905586/95784378-fef47b00-0cd3-11eb-85df-578b9cb94ea2.png)

**Comment by Gregory-Gerard** [comment]
I think this is non-related to themes CSS because video.js core CSS force the liveui button to display: inline-flex and broke vertical alignment.

To fix it, you have to add an `align-items: center` for the class `.video-js .vjs-seek-to-live-control` to center the live button vertically.

__video-js.css__
```css
.video-js .vjs-seek-to-live-control {
  align-items: center; /* here */
}
```

![image](https://user-images.githubusercontent.com/56580353/98818165-74ff1580-242b-11eb-806c-c27f5c6a4461.png)

**Comment by genofire** [comment]
You are correct, okay i create a PR upstream
